### PR TITLE
boards: add support for mps2_an521 qemu based board

### PR DESCRIPTION
**Pull request by uLipe**
This PR adds support of mps2_an521 target which is offered as qemu supported target enabling usage of microROS on Zephyr without having a physical board.

This only supports transport over UDP.

### CODE REVIEW

**Comment by uLipe** [comment]
@pablogs9 @Acuadros95 PTAL

**Comment by pablogs9** [comment]
LGTM, could you add this board to CI?

**Review by pablogs9 — APPROVED** [review]

**Comment by uLipe** [comment]
Done! @pablogs9

**Comment by pablogs9** [comment]
Seems like CI if failing

**Comment by uLipe** [comment]
@pablogs9 I will look on that soon.

**Comment by uLipe** [comment]
Sorry folks, I'm trying to find some time to work on this issue soon.

**Pull request closed without merging**
