### PR TITLE
transports: add mising version.h to serial-usb transport header

### PR DESCRIPTION
**Pull request by uLipe**
Signed-off-by: Felipe Neves <felipe.neves@linaro.org>

### CODE REVIEW

**Comment by uLipe** [comment]
@pablogs9 @Acuadros95 small fix, affects only serial-usb transport.

**Comment by pablogs9** [comment]
@mergify backport main foxy galactic

**Comment by uLipe** [comment]
CI issue seems not related to this PR

**Comment by pablogs9** [comment]
Now ok

**Pull request merged**
