### PR TITLE
resolve conflict with nano option

### PR DESCRIPTION
**Pull request by DenvE**
propose solution to avoid duplicate define of nano.specs

### CODE REVIEW

**Comment by pablogs9** [comment]
Hello thanks for the contribution, could you provide an explanation about this? Where is nano defined in libmicroros? I think that I'm missing something...

**Comment by adamheinrich** [comment]
Hi @DenvE, the changes in 9592d8f26734f30cac213a6d2a8df9656441f820 are nice and resolve issues when `CONFIG_NEWLIB_LIBC_NANO=y` is set but why did you remove them in 373c233081adbad67ffa992d9dce44612fb01f30?

**Comment by pablogs9** [comment]
Is this still necessary after merging https://github.com/micro-ROS/micro_ros_zephyr_module/pull/9?

**Comment by DenvE** [comment]
II think we can remove the cpp flags as proposed by @adamheinrich . so my merge request is no longer valid.
But i think we still need to found out the root cause of the problem in case people do have cpp modules

**Comment by pablogs9** [comment]
Ok thanks @DenvE, let me know when is the ok to merge this PR.

**Comment by Acuadros95** [comment]
Closing due to inactivity, feel free to reopen and update the PR if needed.

**Pull request closed without merging**
